#include "fh8626_audio_fanout.h"

#include <errno.h>
#include <string.h>

void fh_audio_fanout_init(struct fh_audio_fanout *f,uint64_t epoch){if(!f)return;memset(f,0,sizeof(*f));f->epoch=epoch?epoch:1;f->next_seq=1;}
int fh_audio_fanout_set_epoch(struct fh_audio_fanout *f,uint64_t epoch){if(!f||!epoch)return -EINVAL;if(epoch==f->epoch)return 0;memset(f->slot,0,sizeof(f->slot));f->epoch=epoch;f->next_seq=1;f->samples_total=0;return 0;}
int fh_audio_fanout_publish(struct fh_audio_fanout *f,uint64_t pts,uint32_t samples,uint32_t codec,const void *bytes,size_t size,uint64_t *capture_seq){struct fh_audio_frame *s;uint64_t seq;if(!f||!bytes||!size||size>FH_AUDIO_FRAME_MAX||!samples)return -EINVAL;if(f->next_seq==UINT64_MAX||f->samples_total>UINT64_MAX-samples)return -EOVERFLOW;seq=f->next_seq++;s=&f->slot[(seq-1U)%FH_AUDIO_FANOUT_SLOTS];memset(s,0,sizeof(*s));s->epoch=f->epoch;s->capture_seq=seq;s->pts=pts;s->sample_start_total=f->samples_total;s->sample_count=samples;s->codec=codec;s->size=size;memcpy(s->bytes,bytes,size);f->samples_total+=samples;if(capture_seq)*capture_seq=seq;return 0;}
void fh_audio_cursor_subscribe(const struct fh_audio_fanout *f,struct fh_audio_cursor *c){if(!f||!c)return;memset(c,0,sizeof(*c));c->epoch=f->epoch;c->next_seq=f->next_seq;c->next_sample_total=f->samples_total;}
int fh_audio_cursor_read(const struct fh_audio_fanout *f,struct fh_audio_cursor *c,struct fh_audio_frame *out){uint64_t oldest,seq;const struct fh_audio_frame*s;if(!f||!c||!out)return -EINVAL;if(c->epoch!=f->epoch){c->epoch=f->epoch;c->next_seq=f->next_seq;c->next_sample_total=f->samples_total;c->discontinuities++;return 0;}if(c->next_seq>=f->next_seq)return 0;oldest=f->next_seq>FH_AUDIO_FANOUT_SLOTS?f->next_seq-FH_AUDIO_FANOUT_SLOTS:1;if(c->next_seq<oldest){const struct fh_audio_frame*o=&f->slot[(oldest-1U)%FH_AUDIO_FANOUT_SLOTS];c->dropped_frames+=oldest-c->next_seq;if(o->sample_start_total>=c->next_sample_total)c->samples_lost+=o->sample_start_total-c->next_sample_total;c->next_seq=oldest;c->next_sample_total=o->sample_start_total;c->discontinuities++;}seq=c->next_seq;s=&f->slot[(seq-1U)%FH_AUDIO_FANOUT_SLOTS];if(s->capture_seq!=seq||s->epoch!=f->epoch)return -EIO;*out=*s;c->next_seq++;c->next_sample_total=s->sample_start_total+s->sample_count;return 1;}
