#define FH8626_PTZ_TEST 1
#include "fh8626_ptz.c"

#define MAX_EVENTS 70000
struct event { unsigned long request; int id; uint32_t value; struct fh_pwm_config config; };
struct recorder { struct event events[MAX_EVENTS]; int count,saves; struct position_state first_saved,saved; };
static int failures;
#define CHECK(x) do { if (!(x)) { fprintf(stderr,"FAIL %s:%d: %s\n",__func__,__LINE__,#x); failures++; return; } } while (0)

static int record_ioctl(void *opaque,unsigned long request,void *argument){struct recorder *r=opaque;struct event *e;if(r->count>=MAX_EVENTS){errno=ENOSPC;return -1;}e=&r->events[r->count++];memset(e,0,sizeof(*e));e->request=request;if(request==SET_PWM_DUTY_CYCLE||request==DISABLE_PWM){struct fh_pwm_chip_data *d=argument;e->id=d->id;e->config=d->config;}else e->value=*(uint32_t *)argument;return 0;}
static int record_save(void *opaque,const struct position_state *s){struct recorder *r=opaque;if(!r->saves)r->first_saved=*s;r->saves++;r->saved=*s;return 0;}
static void reset(struct recorder *r){memset(r,0,sizeof(*r));backend=(struct backend){record_ioctl,r};skip_hardware_setup=1;save_hook=record_save;save_opaque=r;stop_requested=0;}
static int motion_events(const struct recorder *r){int i,n=0;for(i=0;i<r->count;i++)if(r->events[i].request!=DISABLE_PWM)n++;return n;}

static void test_cycle_contract(void){struct recorder r;uint32_t t=1000000U-70000U,expected[12]={4*t,4*t,2*t,2*t,t,t,t,2*t,2*t,2*t,4*t,4*t};int cycle,ch;reset(&r);CHECK(run_axis_steps_at(&axes[0],12,1000000U)==0);CHECK(motion_events(&r)==12*6);for(cycle=0;cycle<12;cycle++){int base=cycle*6;for(ch=0;ch<4;ch++){struct event *e=&r.events[base+ch];uint32_t q=expected[cycle]/4;CHECK(e->request==SET_PWM_DUTY_CYCLE);CHECK(e->id==axes[0].pwm[ch]);CHECK(e->config.pulses==1);CHECK(e->config.finish_all==(uint32_t)(ch==0));CHECK(e->config.period_ns==expected[cycle]);CHECK(e->config.duty_ns==expected[cycle]/2);CHECK(e->config.phase_ns==(uint32_t)ch*q);CHECK(e->config.stop==(uint32_t)(cycle<11&&ch==3?3:0));}CHECK(r.events[base+4].request==ENABLE_MUL_PWM);CHECK(r.events[base+4].value==((1U<<11)|(1U<<10)|(1U<<9)|(1U<<6)));CHECK(r.events[base+5].request==WAIT_PWM_FINISHALL);CHECK(r.events[base+5].value==11);}}
static void test_negative_and_channel_invert(void){struct recorder r;struct axis a=axes[0];uint32_t p,q;int ch,ids[4]={11,6,9,10};reset(&r);CHECK(run_axis_steps_at(&a,-1,1000000U)==0);p=4*(1000000U-70000U);q=p/4;for(ch=0;ch<4;ch++)CHECK(r.events[ch].config.phase_ns==(uint32_t)(3-ch)*q);reset(&r);apply_axis_inversion(&a);CHECK(run_axis_steps_at(&a,1,1000000U)==0);for(ch=0;ch<4;ch++){CHECK(r.events[ch].id==ids[ch]);CHECK(r.events[ch].config.phase_ns==(uint32_t)ch*q);}CHECK(a.mux[1]==1&&a.mux[3]==0);}
static void test_stock_shared_worker_order(void){struct recorder r;int first[2]={2,2},second[2]={0,0};uint32_t timing[2]={1000000U,1000000U};int i,enables=0,waits=0,seen_tilt=0;reset(&r);CHECK(run_axes_stock(first,second,timing,"test")==0);for(i=0;i<r.count;i++){struct event *e=&r.events[i];if(e->request==SET_PWM_DUTY_CYCLE){CHECK(e->config.pulses==1);if(e->id==5)seen_tilt=1;if(e->id==11)CHECK(!seen_tilt);}else if(e->request==ENABLE_MUL_PWM){int *ids=e->value==((1U<<11)|(1U<<10)|(1U<<9)|(1U<<6))?axes[0].pwm:axes[1].pwm,ch;CHECK(i>=4);for(ch=0;ch<4;ch++){CHECK(r.events[i-4+ch].request==SET_PWM_DUTY_CYCLE);CHECK(r.events[i-4+ch].id==ids[ch]);}enables++;}else if(e->request==WAIT_PWM_FINISHALL){CHECK(e->value==11||e->value==5);waits++;}}CHECK(seen_tilt);CHECK(enables==4&&waits==4);}
static void test_type2_saved_return(void){struct recorder r;struct position_state s={1,1,600,199};int i,pan_cycle=0,tilt_cycle=0;reset(&r);CHECK(calibrate_type2(&s)==0);CHECK(r.saves==2);CHECK(!r.first_saved.valid&&!r.first_saved.calibrated);CHECK(r.saved.valid&&r.saved.calibrated);CHECK(r.saved.pan==600&&r.saved.tilt==199);for(i=0;i<r.count;i++)if(r.events[i].request==SET_PWM_DUTY_CYCLE){struct event *e=&r.events[i];if(e->id==11){uint32_t q=e->config.period_ns/4;if(pan_cycle<1028)CHECK(e->config.phase_ns==0);else if(pan_cycle<2056)CHECK(e->config.phase_ns==3*q);else CHECK(e->config.phase_ns==0);pan_cycle++;}if(e->id==5){uint32_t q=e->config.period_ns/4;if(tilt_cycle<250)CHECK(e->config.phase_ns==0);else if(tilt_cycle<500)CHECK(e->config.phase_ns==3*q);else CHECK(e->config.phase_ns==0);tilt_cycle++;}}CHECK(pan_cycle==1028+1028+(1028-600));CHECK(tilt_cycle==250+250+(250-199));}
static void test_type2_global_stage_order(void){struct recorder r;struct position_state s={1,1,600,199};struct stage{int id,dir,count;} expected[6]={{11,1,1028},{11,-1,1028},{5,1,250},{5,-1,250},{11,1,428},{5,1,51}};int i,stage=0,count=0;reset(&r);CHECK(calibrate_type2(&s)==0);for(i=0;i<r.count;i++)if(r.events[i].request==SET_PWM_DUTY_CYCLE&&(r.events[i].id==11||r.events[i].id==5)){uint32_t q=r.events[i].config.period_ns/4;int dir=r.events[i].config.phase_ns==0?1:r.events[i].config.phase_ns==3*q?-1:0;CHECK(stage<6);CHECK(r.events[i].id==expected[stage].id);CHECK(dir==expected[stage].dir);if(++count==expected[stage].count){stage++;count=0;}}CHECK(stage==6&&count==0);}
static void test_home_fallback(void){struct recorder r;struct position_state s={0,0,0,0};reset(&r);axes[0].invert=0;CHECK(calibrate_type2(&s)==0);CHECK(r.saves==2);CHECK(!r.first_saved.calibrated);CHECK(r.saved.pan==axes[0].home);CHECK(r.saved.tilt==axes[1].home);}
static void test_move_uses_stock_coordinate_sign(void){struct recorder r;struct position_state s={1,1,100,100};int i,pan=-1,tilt=-1;uint32_t q;reset(&r);CHECK(coordinated_move(&s,102,101)==0);CHECK(r.saves==2);CHECK(!r.first_saved.valid&&!r.first_saved.calibrated);CHECK(r.saved.valid&&r.saved.calibrated);CHECK(r.saved.pan==102&&r.saved.tilt==101);for(i=0;i<r.count;i++)if(r.events[i].request==SET_PWM_DUTY_CYCLE){if(pan<0&&r.events[i].id==axes[0].pwm[0])pan=i;if(tilt<0&&r.events[i].id==axes[1].pwm[0])tilt=i;}CHECK(pan>=0&&tilt>pan);q=r.events[pan].config.period_ns/4;CHECK(r.events[pan].config.phase_ns==3*q);q=r.events[tilt].config.period_ns/4;CHECK(r.events[tilt].config.phase_ns==3*q);reset(&r);CHECK(coordinated_move(&s,100,100)==0);pan=tilt=-1;for(i=0;i<r.count;i++)if(r.events[i].request==SET_PWM_DUTY_CYCLE){if(pan<0&&r.events[i].id==axes[0].pwm[0])pan=i;if(tilt<0&&r.events[i].id==axes[1].pwm[0])tilt=i;}CHECK(pan>=0&&tilt>pan);CHECK(r.events[pan].config.phase_ns==0);CHECK(r.events[tilt].config.phase_ns==0);reset(&r);CHECK(coordinated_move(&s,100,100)==0);CHECK(r.saves==0);}
int main(void){test_cycle_contract();test_negative_and_channel_invert();test_stock_shared_worker_order();test_type2_saved_return();test_type2_global_stage_order();test_home_fallback();test_move_uses_stock_coordinate_sign();if(failures){fprintf(stderr,"%d test(s) failed\n",failures);return 1;}puts("fh8626 PTZ tests: PASS");return 0;}
